name: Tests

on:
  - push
  - pull_request

jobs:
  android:
    name: Android
    runs-on: ubuntu-latest
    strategy:
      fail-fast: false
      matrix:
        api-level: [34]
        rn-version: ['0.75', '0.74', '0.73', '0.72', '0.71']
        arch: ['new', 'old']

    steps:
      - uses: actions/checkout@v4

      - name: Free Disk Space (Ubuntu)
        uses: jlumbroso/free-disk-space@main
        with:
          android: false
          # large-packages: true
          # swap-storage: true

      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/setup-node@v4

      - name: Gradle cache
        uses: gradle/actions/setup-gradle@v3
        with:
          # TODO: Remove this after we merge
          cache-read-only: ${{ github.ref != 'refs/heads/master' && github.ref != 'refs/heads/monorepo' }}

      - name: Setup yarn
        run: |
          corepack enable

      - uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --immutable

      - name: AVD Deps
        run: |
          sudo apt update
          sudo apt-get install -y libpulse0 libgl1

      - name: Build
        run: |
          yarn prepare

      - name: AVD cache
        uses: actions/cache@v4
        id: avd-cache
        with:
          path: |
            ~/.android/avd/*
            ~/.android/adb*
          key: avd-${{ matrix.api-level }}

      - name: create AVD and generate snapshot for caching
        if: steps.avd-cache.outputs.cache-hit != 'true'
        uses: reactivecircus/android-emulator-runner@v2
        with:
          profile: pixel_6_pro
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          script: echo "Generated AVD snapshot for caching."

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: Set up RN version
        run: |
          cd packages/icon-explorer

          ./set-rn-version.sh ${{ matrix.arch }} ${{ matrix.rn-version }}

      - name: Build App
        run: |
          cd packages/icon-explorer
          yarn test:android:build

      - name: Run tests
        uses: reactivecircus/android-emulator-runner@v2
        with:
          profile: pixel_6_pro
          api-level: ${{ matrix.api-level }}
          arch: x86_64
          force-avd-creation: false
          emulator-options: -no-snapshot-save -no-window -gpu swiftshader_indirect -noaudio -no-boot-anim -camera-back none
          disable-animations: true
          script: cd packages/icon-explorer && yarn test:android:run

      - name: Build App
        run: |
          echo MOO
          ls -al || true
          echo MOO
          ls -al packages || true
          echo MOO
          ls -al packages/icon-explorer || true
          echo MOO
          ls -al packages/icon-explorer/.owl || true

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.arch }}-${{ matrix.rn-version }}-android
          path: packages/icon-explorer/.owl
          include-hidden-files: true

      # - uses: dorny/test-reporter@v1
      #   if: always()
      #   with:
      #     name: JEST Tests android - ${{ matrix.arch }} ${{ matrix.rn-version }}
      #     path: packages/icon-explorer/.owl/report/*.json
      #     reporter: jest-junit

  ios:
    name: iOS
    runs-on: macos-latest
    strategy:
      fail-fast: false
      matrix:
        rn-version: ['0.75', '0.74', '0.73', '0.72', '0.71']
        arch: ['new', 'old']

    steps:
      - uses: actions/checkout@v4


      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'

      - uses: actions/setup-node@v4

      - name: Setup yarn
        run: |
          corepack enable

      - uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --immutable

      - name: Build
        run: |
          yarn prepare

      - name: Set up RN version
        run: |
          cd packages/icon-explorer

          ./set-rn-version.sh ${{ matrix.arch }} ${{ matrix.rn-version }}

      - name: Run simulatpr
        uses: futureware-tech/simulator-action@v1
        with:
          model: 'iPhone 15'
          os_version: '>=15.0'

      - name: Build App
        run: |
          cd packages/icon-explorer
          # Due to react-native-test-app not bundling
          yarn build:ios:owl
          if [ "${{ matrix.arch }}" = "new" ]; then
            NO_FLIPPER=1 RCT_NEW_ARCH_ENABLED=1 pod update --project-directory=ios
          else
            NO_FLIPPER=1 RCT_NEW_ARCH_ENABLED=0 pod update --project-directory=ios
          fi
          yarn test:ios:build

      - name: Run tests
        run: |
          cd packages/icon-explorer
          yarn test:ios:run

      - uses: actions/upload-artifact@v4
        if: always()
        with:
          name: test-results-${{ matrix.arch }}-${{ matrix.rn-version }}-ios
          path: packages/icon-explorer/.owl
          include-hidden-files: true

      - uses: dorny/test-reporter@v1
        if: always()
        with:
          name: JEST Tests ios - ${{ matrix.arch }} ${{ matrix.rn-version }}
          path: packages/icon-explorer/.owl/report/*.json
          reporter: jest-junit
