name: Tests

on:
  - push
  - pull_request

jobs:
  android:
    name: Android
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-node@v4
      - name: Setup yarn
        run: |
          corepack enable
      - uses: bahmutov/npm-install@v1
      - name: build-app
        run: |
          cd packages/icon-explorer
          yarn build:android
          yarn android
      - name: Run tests
        run: |
          cd packages/icon-explorer
          yarn test
      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            'packages/icon-exporer/e2e/*.xml'
      - name: Publish Diff Images
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: image-diffs
          path: packages/icon-exporer/e2e/diff
