name: Tests

on:
  - push
  - pull_request

jobs:
  android:
    name: Android
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '17'
      - uses: actions/setup-node@v4
      - name: Setup yarn
        run: |
          corepack enable
      - uses: bahmutov/npm-install@v1
        with:
          install-command: yarn --immutable

      - name: Build
        run: |
          yarn prepare

      - name: Enable KVM group perms
        run: |
          echo 'KERNEL=="kvm", GROUP="kvm", MODE="0666", OPTIONS+="static_node=kvm"' | sudo tee /etc/udev/rules.d/99-kvm4all.rules
          sudo udevadm control --reload-rules
          sudo udevadm trigger --name-match=kvm

      - name: build-app
        run: |
          cd packages/icon-explorer
          yarn build:android
          nohup yarn start &

      - uses: malinskiy/action-android/install-sdk@release/0.1.6

      - run: sdkmanager platform-tools

      - name: build-app2
        run: |
          cd packages/icon-explorer
          yarn android

      # - name: Run tests
      #   uses: reactivecircus/android-emulator-runner@v2
      #   with:
      #     api-level: 29
      #     script: ./gradlew connectedCheck
      #
      - name: Run tests
        run: |
          cd packages/icon-explorer
          yarn test

      - name: Publish Test Results
        uses: EnricoMi/publish-unit-test-result-action@v2
        if: always()
        with:
          files: |
            'packages/icon-exporer/e2e/*.xml'
      - name: Publish Diff Images
        uses: actions/upload-artifact@v4
        if: always()
        with:
          name: image-diffs
          path: packages/icon-exporer/e2e/diff
